export const companies = [
  'Alderac Entertainment Group',
  'Allen & Ginter',
  'Bandai',
  'Bench Warmer International',
  'Bowman Gum',
  'Bushiroad',
  'Chaosium',
  'Decipher, Inc.',
  ' Donruss',
  'Fantom (company)',
  'Fleer',
  'The Game Crafter',
  'Goodwin & Company',
  'In the Game Trading Cards',
  'Konami',
  'Leaf Trading Cards',
  'Panini Group',
  'Nintendo',
  'O-Pee-Chee',
  'Pinnacle Brands',
  'Razor Entertainment',
  'SkyBox International',
  'Square Enix',
  'Tomy',
  'Topps',
  'Tristar Productions',
  'Upper Deck Company',
  'Wizards of the Coast',
]
